/// Flutter icons SunMoonAddCal
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SunMoonAddCal
///      fonts:
///       - asset: fonts/SunMoonAddCal.ttf
///
/// 
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///
import 'package:flutter/widgets.dart';

class SunMoonAddCal {
  SunMoonAddCal._();

  static const _kFontFam = 'SunMoonAddCal';
  static const _kFontPkg = null;

  static const IconData cal = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_outline = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
